"""empty message

Revision ID: 8ea18a708df7
Revises: 9d5160bc4478
Create Date: 2026-02-08 18:33:04.828028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ea18a708df7'
down_revision = '9d5160bc4478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('surname', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('birthdate', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('is_professional_dancer', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('ubication_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['nickname'])
        batch_op.create_foreign_key(None, 'ubication', ['ubication_id'], ['id'])
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('ubication_id')
        batch_op.drop_column('is_professional_dancer')
        batch_op.drop_column('birthdate')
        batch_op.drop_column('surname')
        batch_op.drop_column('name')
        batch_op.drop_column('nickname')

    # ### end Alembic commands ###
