"""empty message

Revision ID: d34986dd118e
Revises: 8354cce3889b
Create Date: 2026-02-12 17:39:12.616031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd34986dd118e'
down_revision = '8354cce3889b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('comment_post_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('comment_user_id_fkey'), type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('post_id')

    with op.batch_alter_table('image_post', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('image_post_post_id_fkey'), type_='foreignkey')
        batch_op.drop_column('post_id')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('post_usuario_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('post_ubicacion_id_fkey'), type_='foreignkey')
        batch_op.drop_column('ubicacion_id')
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('ubicacion_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('post_ubicacion_id_fkey'), 'ubication', ['ubicacion_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('post_usuario_id_fkey'), 'user', ['usuario_id'], ['id'])
        batch_op.alter_column('description',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('image_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('image_post_post_id_fkey'), 'post', ['post_id'], ['id'])

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('comment_user_id_fkey'), 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('comment_post_id_fkey'), 'post', ['post_id'], ['id'])

    # ### end Alembic commands ###
