"""empty message

Revision ID: dca22e3d01b6
Revises: 8ea18a708df7
Create Date: 2026-02-10 20:47:46.103410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dca22e3d01b6'
down_revision = '8ea18a708df7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('schedule', sa.String(length=15), nullable=False),
    sa.Column('styles', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('contact_number', sa.Integer(), nullable=False),
    sa.Column('owner_name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
